spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
    auth-code-expiration-millis: 300000  # 5 * 60 * 1000 == 30분



  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql : true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${jwt.secret.key}
  access-token-expiration-millis : 1800000 # 1000 * 60 * 30;            // 30분
  refresh-token-expiration-millis : 604800000 # 1000 * 60 * 60 * 24 * 7;  // 7일
  